export const SET_DISTRICT = "SET_DISTRICT";

export const GET_DISTRICTS_IN_PROVINCE_REQUESTED =
  "GET_DISTRICTS_IN_PROVINCE_REQUESTED";
export const GET_DISTRICTS_IN_PROVINCE_SUCCEEDED =
  "GET_DISTRICTS_IN_PROVINCE_SUCCEEDED";
export const GET_DISTRICTS_IN_PROVINCE_FAILED =
  "GET_DISTRICTS_IN_PROVINCE_FAILED";

export const GET_DISTRICTS_REQUESTED = "GET_DISTRICTS_REQUESTED";
export const GET_DISTRICTS_SUCCEEDED = "GET_DISTRICTS_SUCCEEDED";
export const GET_DISTRICTS_FAILED = "GET_DISTRICTS_FAILED";

export const ADD_DISTRICT_REQUESTED = "ADD_DISTRICT_REQUESTED";
export const ADD_DISTRICT_SUCCEEDED = "ADD_DISTRICT_SUCCEEDED";
export const ADD_DISTRICT_FAILED = "ADD_DISTRICT_FAILED";

export const EDIT_DISTRICT_REQUESTED = "EDIT_DISTRICT_REQUESTED";
export const EDIT_DISTRICT_SUCCEEDED = "EDIT_DISTRICT_SUCCEEDED";
export const EDIT_DISTRICT_FAILED = "EDIT_DISTRICT_FAILED";

export const DELETE_DISTRICT_REQUESTED = "DELETE_DISTRICT_REQUESTED";
export const DELETE_DISTRICT_SUCCEEDED = "DELETE_DISTRICT_SUCCEEDED";
export const DELETE_DISTRICT_FAILED = "DELETE_DISTRICT_FAILED";
