export const SET_EMPLOYEE_CERTIFICATE = "SET_EMPLOYEE_CERTIFICATE";

export const GET_EMPLOYEE_CERTIFICATES_REQUESTED =
  "GET_EMPLOYEE_CERTIFICATES_REQUESTED";
export const GET_EMPLOYEE_CERTIFICATES_SUCCEEDED =
  "GET_EMPLOYEE_CERTIFICATES_SUCCEEDED";
export const GET_EMPLOYEE_CERTIFICATES_FAILED =
  "GET_EMPLOYEE_CERTIFICATES_FAILED";

export const ADD_EMPLOYEE_CERTIFICATE_REQUESTED =
  "ADD_EMPLOYEE_CERTIFICATE_REQUESTED";
export const ADD_EMPLOYEE_CERTIFICATE_SUCCEEDED =
  "ADD_EMPLOYEE_CERTIFICATE_SUCCEEDED";
export const ADD_EMPLOYEE_CERTIFICATE_FAILED =
  "ADD_EMPLOYEE_CERTIFICATE_FAILED";

export const EDIT_EMPLOYEE_CERTIFICATE_REQUESTED =
  "EDIT_EMPLOYEE_CERTIFICATE_REQUESTED";
export const EDIT_EMPLOYEE_CERTIFICATE_SUCCEEDED =
  "EDIT_EMPLOYEE_CERTIFICATE_SUCCEEDED";
export const EDIT_EMPLOYEE_CERTIFICATE_FAILED =
  "EDIT_EMPLOYEE_CERTIFICATE_FAILED";

export const DELETE_EMPLOYEE_CERTIFICATE_REQUESTED =
  "DELETE_EMPLOYEE_CERTIFICATE_REQUESTED";
export const DELETE_EMPLOYEE_CERTIFICATE_SUCCEEDED =
  "DELETE_EMPLOYEE_CERTIFICATE_SUCCEEDED";
export const DELETE_EMPLOYEE_CERTIFICATE_FAILED =
  "DELETE_EMPLOYEE_CERTIFICATE_FAILED";
