export const SET_CERTIFICATE = "SET_CERTIFICATE";

export const GET_CERTIFICATES_REQUESTED = "GET_CERTIFICATES_REQUESTED";
export const GET_CERTIFICATES_SUCCEEDED = "GET_CERTIFICATES_SUCCEEDED";
export const GET_CERTIFICATES_FAILED = "GET_CERTIFICATES_FAILED";

export const ADD_CERTIFICATE_REQUESTED = "ADD_CERTIFICATE_REQUESTED";
export const ADD_CERTIFICATE_SUCCEEDED = "ADD_CERTIFICATE_SUCCEEDED";
export const ADD_CERTIFICATE_FAILED = "ADD_CERTIFICATE_FAILED";

export const EDIT_CERTIFICATE_REQUESTED = "EDIT_CERTIFICATE_REQUESTED";
export const EDIT_CERTIFICATE_SUCCEEDED = "EDIT_CERTIFICATE_SUCCEEDED";
export const EDIT_CERTIFICATE_FAILED = "EDIT_CERTIFICATE_FAILED";

export const DELETE_CERTIFICATE_REQUESTED = "DELETE_CERTIFICATE_REQUESTED";
export const DELETE_CERTIFICATE_SUCCEEDED = "DELETE_CERTIFICATE_SUCCEEDED";
export const DELETE_CERTIFICATE_FAILED = "DELETE_CERTIFICATE_FAILED";
