export const SET_EMPLOYEE = "SET_EMPLOYEE";

export const GET_EMPLOYEES_REQUESTED = "GET_EMPLOYEES_REQUESTED";
export const GET_EMPLOYEES_SUCCEEDED = "GET_EMPLOYEES_SUCCEEDED";
export const GET_EMPLOYEES_FAILED = "GET_EMPLOYEES_FAILED";

export const ADD_EMPLOYEE_REQUESTED = "ADD_EMPLOYEE_REQUESTED";
export const ADD_EMPLOYEE_SUCCEEDED = "ADD_EMPLOYEE_SUCCEEDED";
export const ADD_EMPLOYEE_FAILED = "ADD_EMPLOYEE_FAILED";

export const EDIT_EMPLOYEE_REQUESTED = "EDIT_EMPLOYEE_REQUESTED";
export const EDIT_EMPLOYEE_SUCCEEDED = "EDIT_EMPLOYEE_SUCCEEDED";
export const EDIT_EMPLOYEE_FAILED = "EDIT_EMPLOYEE_FAILED";

export const DELETE_EMPLOYEE_REQUESTED = "DELETE_EMPLOYEE_REQUESTED";
export const DELETE_EMPLOYEE_SUCCEEDED = "DELETE_EMPLOYEE_SUCCEEDED";
export const DELETE_EMPLOYEE_FAILED = "DELETE_EMPLOYEE_FAILED";
