export const SET_PROVINCE = "SET_PROVINCE";

export const GET_PROVINCES_REQUESTED = "GET_PROVINCES_REQUESTED";
export const GET_PROVINCES_SUCCEEDED = "GET_PROVINCES_SUCCEEDED";
export const GET_PROVINCES_FAILED = "GET_PROVINCES_FAILED";

export const ADD_PROVINCE_REQUESTED = "ADD_PROVINCE_REQUESTED";
export const ADD_PROVINCE_SUCCEEDED = "ADD_PROVINCE_SUCCEEDED";
export const ADD_PROVINCE_FAILED = "ADD_PROVINCE_FAILED";

export const EDIT_PROVINCE_REQUESTED = "EDIT_PROVINCE_REQUESTED";
export const EDIT_PROVINCE_SUCCEEDED = "EDIT_PROVINCE_SUCCEEDED";
export const EDIT_PROVINCE_FAILED = "EDIT_PROVINCE_FAILED";

export const DELETE_PROVINCE_REQUESTED = "DELETE_PROVINCE_REQUESTED";
export const DELETE_PROVINCE_SUCCEEDED = "DELETE_PROVINCE_SUCCEEDED";
export const DELETE_PROVINCE_FAILED = "DELETE_PROVINCE_FAILED";
