export const SET_WARD = "SET_WARD";

export const GET_WARDS_IN_DISTRICT_REQUESTED =
  "GET_WARDS_IN_DISTRICT_REQUESTED";
export const GET_WARDS_IN_DISTRICT_SUCCEEDED =
  "GET_WARDS_IN_DISTRICT_SUCCEEDED";
export const GET_WARDS_IN_DISTRICT_FAILED = "GET_WARDS_IN_DISTRICT_FAILED";

export const GET_WARDS_REQUESTED = "GET_WARDS_REQUESTED";
export const GET_WARDS_SUCCEEDED = "GET_WARDS_SUCCEEDED";
export const GET_WARDS_FAILED = "GET_WARDS_FAILED";

export const ADD_WARD_REQUESTED = "ADD_WARD_REQUESTED";
export const ADD_WARD_SUCCEEDED = "ADD_WARD_SUCCEEDED";
export const ADD_WARD_FAILED = "ADD_WARD_FAILED";

export const EDIT_WARD_REQUESTED = "EDIT_WARD_REQUESTED";
export const EDIT_WARD_SUCCEEDED = "EDIT_WARD_SUCCEEDED";
export const EDIT_WARD_FAILED = "EDIT_WARD_FAILED";

export const DELETE_WARD_REQUESTED = "DELETE_WARD_REQUESTED";
export const DELETE_WARD_SUCCEEDED = "DELETE_WARD_SUCCEEDED";
export const DELETE_WARD_FAILED = "DELETE_WARD_FAILED";
